@startdot

digraph costing_plan {

  POS_Catalog -> POS_Catalog_Item

  POS_Catalog_Item -> Price
  POS_Catalog_Item -> Customer_Option
  POS_Catalog_Item -> Menu_Item_Name

  Customer_Option -> POS_Line_Item

  POS_Line_Item -> Packaging
  POS_Line_Item -> Ingredient

  Packaging -> Cost
  Ingredient -> Cost

  Packaging -> Markup
  Ingredient -> Markup

  Markup -> Price
  Cost -> Price

  POS_Line_Item [
    shape=record
    label = "{Transaction Item |16 ounce 2 shot oat milk latte to go}"
  ]

  Menu_Item_Name [
    shape=record
    label="{Menu Item|Latte}"
    style=filled
    fillcolor=yellow
  ]

  Customer_Option [
    shape=record
    label = "{Customer Option|size|shots|milk|cup}"
    style=filled
    fillcolor=yellow
  ]

  Ingredient [
    shape=record
    label = "{Ingredient|oat milk, espresso}"
  ]

  Packaging [
    shape=record
    label = "{Packaging|cup, lid, sleeve}"
  ]

  POS_Catalog [
    shape=record
    label="{Point of Sale Catalog|Square}"
  ]

  POS_Catalog_Item [
    shape=record
    label="{Catalog Item|Latte}"
  ]

  Markup [
    shape=record
    label="{Markup|3.5x}"
  ]

  Cost [
    shape=record
    label="{Cost|$1.50}"
  ]

  Price [
    shape=record
    label="{Price|$5.25}"
    style=filled
    fillcolor=yellow
  ]
}

@enddot
