# The goal of the workflow is to customize our deployment to GitHub pages. 
# See https://github.com/actions/deploy-pages/issues/20
# See also https://github.com/actions/deploy-pages/issues/9

permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

name: Build and Deploy

on:
  push:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Archive build output
      run: tar --dereference --hard-dereference --directory docs/ -cvf artifact.tar .
    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ./artifact.tar
        if-no-files-found: warn
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
